### ISSUE TITLE
crashes on fast output

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dragonlinux/connectbot#141]
```
Portrait mode, running 'aptitude update' (which results in heavy text
output) crashes the app.
```

Original issue reported on code.google.com by `gsm...@gmail.com` on 18 Apr 2009 at 1:57

**Comment by GoogleCodeExporter** [comment]
```
Do you have the Android SDK installed? The output of "adb logcat" after this
occurrence would be immensely informative. Also, which version and build are 
you running?
```

Original comment by `kenny@the-b.org` on 18 Apr 2009 at 12:33

**Comment by GoogleCodeExporter** [comment]
```
Running the officially available SDK 1.1. Here's the stack trace:
--
D/AndroidRuntime(  282): Shutting down VM
W/dalvikvm(  282): threadid=3: thread exiting with uncaught exception (group=0x4
000fe68)
E/AndroidRuntime(  282): Uncaught handler: thread main exiting due to uncaught e
xception
E/AndroidRuntime(  282): java.lang.ArrayIndexOutOfBoundsException
E/AndroidRuntime(  282):        at org.connectbot.service.TerminalBridge.onDraw(
TerminalBridge.java:1363)
E/AndroidRuntime(  282):        at org.connectbot.TerminalView.onDraw(TerminalVi
ew.java:140)
E/AndroidRuntime(  282):        at android.view.View.draw(View.java:5462)
E/AndroidRuntime(  282):        at android.view.ViewGroup.drawChild(ViewGroup.ja
va:1436)
E/AndroidRuntime(  282):        at android.view.ViewGroup.dispatchDraw(ViewGroup
.java:1208)
E/AndroidRuntime(  282):        at android.view.ViewGroup.drawChild(ViewGroup.ja
va:1434)
E/AndroidRuntime(  282):        at android.view.ViewGroup.dispatchDraw(ViewGroup
.java:1208)
E/AndroidRuntime(  282):        at android.view.ViewGroup.drawChild(ViewGroup.ja
va:1434)
E/AndroidRuntime(  282):        at android.view.ViewGroup.dispatchDraw(ViewGroup
.java:1208)
E/AndroidRuntime(  282):        at android.view.View.draw(View.java:5465)
E/AndroidRuntime(  282):        at android.view.ViewGroup.drawChild(ViewGroup.ja
va:1436)
E/AndroidRuntime(  282):        at android.view.ViewGroup.dispatchDraw(ViewGroup
.java:1208)
E/AndroidRuntime(  282):        at android.view.ViewGroup.drawChild(ViewGroup.ja
va:1434)
E/AndroidRuntime(  282):        at android.view.ViewGroup.dispatchDraw(ViewGroup
.java:1208)
E/AndroidRuntime(  282):        at android.view.View.draw(View.java:5465)
E/AndroidRuntime(  282):        at android.widget.FrameLayout.draw(FrameLayout.j
ava:324)
E/AndroidRuntime(  282):        at com.android.internal.policy.impl.PhoneWindow$
DecorView.draw(PhoneWindow.java:1733)
E/AndroidRuntime(  282):        at android.view.ViewRoot.draw(ViewRoot.java:980)

E/AndroidRuntime(  282):        at android.view.ViewRoot.performTraversals(ViewR
oot.java:829)
E/AndroidRuntime(  282):        at android.view.ViewRoot.handleMessage(ViewRoot.
java:1103)
E/AndroidRuntime(  282):        at android.os.Handler.dispatchMessage(Handler.ja
va:88)
E/AndroidRuntime(  282):        at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime(  282):        at android.app.ActivityThread.main(ActivityThrea
d.java:3739)
E/AndroidRuntime(  282):        at java.lang.reflect.Method.invokeNative(Native
Method)
E/AndroidRuntime(  282):        at java.lang.reflect.Method.invoke(Method.java:5
15)
E/AndroidRuntime(  282):        at com.android.internal.os.ZygoteInit$MethodAndA
rgsCaller.run(ZygoteInit.java:739)
E/AndroidRuntime(  282):        at com.android.internal.os.ZygoteInit.main(Zygot
eInit.java:497)
E/AndroidRuntime(  282):        at dalvik.system.NativeStart.main(Native Method)
--
```

Original comment by `gsm...@gmail.com` on 18 Apr 2009 at 12:51

**Comment by GoogleCodeExporter** [comment]
```
Was this while resizing the screen by chance?
```

Original comment by `kenny@the-b.org` on 5 May 2009 at 10:06

**Comment by GoogleCodeExporter** [comment]
```
Nope, didn't touch anything.
```

Original comment by `gsm...@gmail.com` on 5 May 2009 at 10:10

**Comment by GoogleCodeExporter** [comment]
```
Hm, I haven't been able to reproduce this. Can you run "apititude update" while 
in a
"script" session and attach the output here? That way I should be able to just 
cat
the file and have it draw all the output you see that causes the issue.
```

Original comment by `kenny@the-b.org` on 5 May 2009 at 10:22

**Comment by GoogleCodeExporter** [comment]
```
Me neither. :)
Didn't reproduce on cupcake emulator + svn head.
```

Original comment by `gsm...@gmail.com` on 6 May 2009 at 8:59

**Comment by GoogleCodeExporter** [comment]
```
I'll close this as won't fix unless we get some more reports
```

Original comment by `kenny@the-b.org` on 14 May 2009 at 5:53
- Changed state: **WontFix**
