### ISSUE TITLE
entering 'top' in remote forwarded ssh connection will terminate original ssh connection

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dragonlinux/connectbot#241]
```
What steps will reproduce the problem?
1. set up a remote forward 22222:destinationhost:22 (destinationhost must
be reachable directly from your phone, the original intention was to make
an ssh tunnel to the ssh server running on my phone, but it's not necessary
to have an ssh server on your phone to reproduce this)
2. on remote host, ssh -p 22222 user@destinationhost
3. type 'ls<return>', which works
4. type 'top<return>', which disconnects the connection to the original
hosts in connectbot

What is the expected output? What do you see instead?
expected: top screen

instead:
Connection to localhost closed by remote host.
Connection to localhost closed.


What version of the product are you using (you can see this by using Menu
-> About in the Host List)?
r434

What type of system are you trying to connect to?
linux

If you are able to connect, what is the output of "echo $TERM", "uname -a",
and any other relevant information on the host?
screen-256color
Linux destinationhost 2.6.22.19-0.4-default #1 SMP 2009-08-14 02:09:16
+0200 x86_64 x86_
64 x86_64 GNU/Linux

Please provide any additional information below.

I have a backtrace. The "WIN DEATH" start as soon as I enter top:

I/ActivityManager( 3016): Process com.android.settings (pid 4517) has died.
I/WindowManager( 3016): WIN DEATH: Window{43ee0018
com.android.settings/com.android.settings.DevelopmentSettings paused=false}
I/WindowManager( 3016): WIN DEATH: Window{43f4b168
com.android.settings/com.android.settings.Settings paused=false}
I/WindowManager( 3016): WIN DEATH: Window{43f5a4b0
com.android.settings/com.android.settings.ApplicationSettings paused=false}
I/ActivityManager( 3016): Low Memory: No more background processes.
D/skia    ( 3986): purging 141K from font cache [16 entries]
D/dalvikvm( 3986): GC freed 6463 objects / 328640 bytes in 230ms
D/dalvikvm( 3307): GC freed 4138 objects / 223248 bytes in 201ms
W/dalvikvm( 3986): threadid=19: thread exiting with uncaught exception
(group=0x4001e170)
D/UNHANDLED_EXCEPTION( 3986): Writing unhandled exception to:
/data/data/org.connectbot/files/1.6-dev-37857.stacktrace
E/ConnectBot.Relay( 3986): Problem while handling incoming data in relay thread
E/ConnectBot.Relay( 3986): java.io.IOException: Remote end closed connection
E/ConnectBot.Relay( 3986):      at
org.connectbot.transport.SSH.read(SSH.java:521)
E/ConnectBot.Relay( 3986):      at
org.connectbot.service.Relay.run(Relay.java:129)
E/ConnectBot.Relay( 3986):      at java.lang.Thread.run(Thread.java:1096)
W/System.err( 3986): java.io.FileNotFoundException:
/data/data/org.connectbot/files/1.6-dev-37857.stacktrace
W/System.err( 3986):    at
org.apache.harmony.luni.platform.OSFileSystem.open(OSFileSystem.java:244)
W/System.err( 3986):    at
java.io.FileOutputStream.<init>(FileOutputStream.java:97)
W/System.err( 3986):    at
java.io.FileOutputStream.<init>(FileOutputStream.java:69)
W/System.err( 3986):    at java.io.FileWriter.<init>(FileWriter.java:80)
W/System.err( 3986):    at
com.nullwire.trace.DefaultExceptionHandler.uncaughtException(DefaultExceptionHan
dler.java:32)
W/System.err( 3986):    at
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:887)
W/System.err( 3986):    at
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:884)
D/UNHANDLED_EXCEPTION( 3986): java.lang.ArrayIndexOutOfBoundsException
D/UNHANDLED_EXCEPTION( 3986):   at java.lang.System.arraycopy(Native Method)
D/UNHANDLED_EXCEPTION( 3986):   at
com.trilead.ssh2.compression.Zlib.compress(Zlib.java:66)
D/UNHANDLED_EXCEPTION( 3986):   at
com.trilead.ssh2.transport.TransportConnection.sendMessage(TransportConnection.j
ava:157)
D/UNHANDLED_EXCEPTION( 3986):   at
com.trilead.ssh2.transport.TransportConnection.sendMessage(TransportConnection.j
ava:134)
D/UNHANDLED_EXCEPTION( 3986):   at
com.trilead.ssh2.transport.TransportManager.sendMessage(TransportManager.java:67
6)
D/UNHANDLED_EXCEPTION( 3986):   at
com.trilead.ssh2.channel.ChannelManager.sendData(ChannelManager.java:439)
D/UNHANDLED_EXCEPTION( 3986):   at
com.trilead.ssh2.channel.ChannelOutputStream.write(ChannelOutputStream.java:64)
D/UNHANDLED_EXCEPTION( 3986):   at
com.trilead.ssh2.channel.StreamForwarder.run(StreamForwarder.java:48)
D/UNHANDLED_EXCEPTION( 3986):   at
com.trilead.ssh2.channel.RemoteAcceptThread.run(RemoteAcceptThread.java:64)
D/dalvikvm( 3075): GC freed 581 objects / 19768 bytes in 179ms
D/dalvikvm( 3072): GC freed 153 objects / 5760 bytes in 120ms
D/dalvikvm( 3605): GC freed 942 objects / 56384 bytes in 126ms
D/dalvikvm( 3323): GC freed 174 objects / 8256 bytes in 86ms
D/skia    ( 3016): purging 51K from font cache [7 entries]
D/dalvikvm( 3016): GC freed 1754 objects / 76320 bytes in 284ms
D/skia    ( 3811): purging 6K from font cache [1 entries]
D/dalvikvm( 3811): GC freed 1040 objects / 71448 bytes in 170ms


```

Original issue reported on code.google.com by `tau...@gmail.com` on 16 Dec 2009 at 9:58

**Comment by GoogleCodeExporter** [comment]
```
Compression was enabled on that host.

There's no disconnect if I disable compression.
```

Original comment by `tau...@gmail.com` on 16 Dec 2009 at 10:14

**Comment by GoogleCodeExporter** [comment]
```
r439 should fix this bug
```

Original comment by `kenny@the-b.org` on 17 Dec 2009 at 7:27
- Changed state: **Fixed**
