### ISSUE TITLE
Application crash at startup

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dragonlinux/connectbot#315]
```
What steps will reproduce the problem?
1. Launch ConnectBot
2. The app will crash with the following logs:

I/dalvikvm( 7532): Debugger thread not active, ignoring DDM send (t=0x41504e4d 
l=38)
I/dalvikvm( 7532): Debugger thread not active, ignoring DDM send (t=0x41504e4d 
l=32)
I/com.nullwire.trace.ExceptionsHandler( 7532): Registering default exceptions 
handler
D/com.nullwire.trace.ExceptionsHandler( 7532): APP_VERSION: 1.7.0-rc1
D/com.nullwire.trace.ExceptionsHandler( 7532): APP_PACKAGE: org.connectbot
D/com.nullwire.trace.ExceptionsHandler( 7532): FILES_PATH: 
/data/data/org.connectbot/files
D/com.nullwire.trace.ExceptionsHandler( 7532): URL: 
http://connectbot.the-b.org/trace/
D/com.nullwire.trace.ExceptionsHandler( 7532): current handler 
class=com.android.internal.os.RuntimeInit$UncaughtHandler

I/ActivityManager(   60): Starting activity: Intent { 
comp={org.connectbot/org.connectbot.WizardActivity} }
D/com.nullwire.trace.ExceptionsHandler( 7532): number of stack traces: 5
I/ConnectBot.TerminalManager( 7532): Starting background service
I/com.nullwire.trace.ExceptionsHandler( 7532): Registering default exceptions 
handler
D/com.nullwire.trace.ExceptionsHandler( 7532): APP_VERSION: 1.7.0-rc1
D/com.nullwire.trace.ExceptionsHandler( 7532): APP_PACKAGE: org.connectbot
D/com.nullwire.trace.ExceptionsHandler( 7532): FILES_PATH: 
/data/data/org.connectbot/files
D/com.nullwire.trace.ExceptionsHandler( 7532): URL: 
http://connectbot.the-b.org/trace/
D/com.nullwire.trace.ExceptionsHandler( 7532): current handler 
class=com.nullwire.trace.DefaultExceptionHandler
I/ConnectBot.TerminalManager( 7532): Someone bound to TerminalManager
I/AlertDialog( 7532): [onCreate] auto launch SIP.
D/dalvikvm( 7532): GC freed 3598 objects / 217104 bytes in 121ms
D/ConnectBot.ConnectivityManager( 7532): onReceived() called; noConnectivity? 
false; isFailover? false
W/InputManagerService(   60): Got RemoteException sending setActive(false) 
notification to pid 7511 uid 10052
I/ActivityManager(   60): Displayed activity org.connectbot/.WizardActivity: 
1441 ms
I/ConnectBot.TerminalManager( 7532): Someone unbound from TerminalManager
D/ConnectBot.TerminalManager( 7532): Stopping background service immediately
I/ActivityManager(   60): Stopping service: 
org.connectbot/.service.TerminalManager
I/ConnectBot.TerminalManager( 7532): Destroying background service
D/dalvikvm( 7532): DexOpt: couldn't find static field
W/dalvikvm( 7532): VFY: unable to resolve static field 37 (SDK_INT) in 
Landroid/os/Build$VERSION;
W/dalvikvm( 7532): VFY:  rejecting opcode 0x60 at 0x0018
W/dalvikvm( 7532): VFY:  rejected 
Lorg/connectbot/util/PreferenceConstants;.<clinit> ()V
W/dalvikvm( 7532): Verifier rejected class 
Lorg/connectbot/util/PreferenceConstants;
D/AndroidRuntime( 7532): Shutting down VM
W/dalvikvm( 7532): threadid=3: thread exiting with uncaught exception 
(group=0x40013140)
D/UNHANDLED_EXCEPTION( 7532): Writing unhandled exception to: 
/data/data/org.connectbot/files/1.7.0-rc1-49661.stacktrace

I/global  ( 7532): Default buffer size used in BufferedWriter constructor. It 
would be better to be explicit if an 8k-ch
ar buffer is required.
D/UNHANDLED_EXCEPTION( 7532): java.lang.VerifyError: 
org.connectbot.util.PreferenceConstants
D/UNHANDLED_EXCEPTION( 7532):   at 
org.connectbot.service.ConnectionNotifier.getInstance(ConnectionNotifier.java:45
)
D/UNHANDLED_EXCEPTION( 7532):   at 
org.connectbot.service.TerminalManager.onDestroy(TerminalManager.java:197)
D/UNHANDLED_EXCEPTION( 7532):   at 
android.app.ActivityThread.handleStopService(ActivityThread.java:2578)
D/UNHANDLED_EXCEPTION( 7532):   at 
android.app.ActivityThread.access$3200(ActivityThread.java:112)
D/UNHANDLED_EXCEPTION( 7532):   at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
D/UNHANDLED_EXCEPTION( 7532):   at 
android.os.Handler.dispatchMessage(Handler.java:99)
D/UNHANDLED_EXCEPTION( 7532):   at android.os.Looper.loop(Looper.java:123)
D/UNHANDLED_EXCEPTION( 7532):   at 
android.app.ActivityThread.main(ActivityThread.java:3948)
D/UNHANDLED_EXCEPTION( 7532):   at java.lang.reflect.Method.invokeNative(Native 
Method)
D/UNHANDLED_EXCEPTION( 7532):   at 
java.lang.reflect.Method.invoke(Method.java:521)
D/UNHANDLED_EXCEPTION( 7532):   at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:782)
D/UNHANDLED_EXCEPTION( 7532):   at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:540)
D/UNHANDLED_EXCEPTION( 7532):   at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 7532): Uncaught handler: thread main exiting due to uncaught 
exception
E/AndroidRuntime( 7532): java.lang.VerifyError: 
org.connectbot.util.PreferenceConstants
E/AndroidRuntime( 7532):        at 
org.connectbot.service.ConnectionNotifier.getInstance(ConnectionNotifier.java:45
)
E/AndroidRuntime( 7532):        at 
org.connectbot.service.TerminalManager.onDestroy(TerminalManager.java:197)
E/AndroidRuntime( 7532):        at 
android.app.ActivityThread.handleStopService(ActivityThread.java:2578)
E/AndroidRuntime( 7532):        at 
android.app.ActivityThread.access$3200(ActivityThread.java:112)
E/AndroidRuntime( 7532):        at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
E/AndroidRuntime( 7532):        at 
android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7532):        at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 7532):        at 
android.app.ActivityThread.main(ActivityThread.java:3948)
E/AndroidRuntime( 7532):        at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime( 7532):        at 
java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime( 7532):        at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:782)
E/AndroidRuntime( 7532):        at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:540)
E/AndroidRuntime( 7532):        at dalvik.system.NativeStart.main(Native Method)
D/InetAddress( 7532): connectbot.googlecode.com: 74.125.77.82 (family 2, proto 
6)
I/Process (   60): Sending signal. PID: 7532 SIG: 3
I/dalvikvm( 7532): threadid=7: reacting to signal 3
I/AlertDialog(   60): [onCreate] auto launch SIP.
D/dalvikvm( 5707): GC freed 6905 objects / 320936 bytes in 228ms
D/dalvikvm( 7143): GC freed 3294 objects / 174136 bytes in 165ms
D/dalvikvm( 7183): GC freed 1805 objects / 160592 bytes in 141ms
D/dalvikvm(  115): GC freed 138 objects / 5592 bytes in 377ms
D/dalvikvm(  165): GC freed 278 objects / 11240 bytes in 276ms
D/dalvikvm( 7344): GC freed 5338 objects / 395792 bytes in 135ms


What version of the product are you using (you can see this by using Menu
-> About in the Host List)?
SVN r505 ALL


What type of system are you trying to connect to?
N.A.

If you are able to connect, what is the output of "echo $TERM", "uname -a",
and any other relevant information on the host?
N.A.

Please provide any additional information below.
I was trying this version to check if the 100% cpu bug is resolved ...
```

Original issue reported on code.google.com by `alexandr...@gmail.com` on 24 Jun 2010 at 11:54

**Comment by GoogleCodeExporter** [comment]
```
The terminal is a HTC Hero with Android 1.5
```

Original comment by `alexandr...@gmail.com` on 24 Jun 2010 at 11:57

**Comment by GoogleCodeExporter** [comment]
```
Okay, this must be a problem with Proguard.
```

Original comment by `kenny@the-b.org` on 25 Jun 2010 at 3:50
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I have the same error on a Samsuny Galaxy running Android 1.5
```

Original comment by `Marcel...@gmail.com` on 29 Jul 2010 at 6:32

**Comment by GoogleCodeExporter** [comment]
```
Whoops. I used SDK_INT when we're minSdkVersion 3. Check r510 or later on 
connectbot.org for a working version.
```

Original comment by `kenny@the-b.org` on 4 Aug 2010 at 5:04
- Changed state: **Fixed**
