### ISSUE TITLE
NPE when editing edit.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dragonlinux/connectbot#36]
```
What steps will reproduce the problem?
1) Edit a host
2) Hit back

What version of the product are you using? On what operating system?
r80

Please provide any additional information below.

E/AndroidRuntime( 1173): java.lang.RuntimeException: Failure delivering
result ResultInfo{who=null, request=1, result=0, data=null} to activity
{org.connectbot/org.connectbot.HostListActivity}:
java.lang.NullPointerException
E/AndroidRuntime( 1173):    at
android.app.ActivityThread.deliverResults(ActivityThread.java:2839)
E/AndroidRuntime( 1173):    at
android.app.ActivityThread.handleSendResult(ActivityThread.java:2881)
E/AndroidRuntime( 1173):    at
android.app.ActivityThread.access$2300(ActivityThread.java:112)
E/AndroidRuntime( 1173):    at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1608)
E/AndroidRuntime( 1173):    at
android.os.Handler.dispatchMessage(Handler.java:88)
E/AndroidRuntime( 1173):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 1173):    at
android.app.ActivityThread.main(ActivityThread.java:3742)
E/AndroidRuntime( 1173):    at java.lang.reflect.Method.invokeNative(Native
Method)
E/AndroidRuntime( 1173):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1173):    at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
E/AndroidRuntime( 1173):    at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:497)
E/AndroidRuntime( 1173):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1173): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 1173):    at
org.connectbot.HostListActivity.updateCursor(HostListActivity.java:297)
E/AndroidRuntime( 1173):    at
org.connectbot.HostListActivity.onActivityResult(HostListActivity.java:148)
E/AndroidRuntime( 1173):    at
android.app.Activity.dispatchActivityResult(Activity.java:3415)
E/AndroidRuntime( 1173):    at
android.app.ActivityThread.deliverResults(ActivityThread.java:2835)
E/AndroidRuntime( 1173):    ... 11 more



```

Original issue reported on code.google.com by `arm...@gmail.com` on 26 Oct 2008 at 5:01

**Comment by GoogleCodeExporter** [comment]
```
This should be fixed in SVN r81 and it's included in the 1.01 Android Market 
release.
```

Original comment by `kenny@the-b.org` on 27 Oct 2008 at 8:12
- Changed state: **Fixed**
